#!/bin/bash
#
# Can you handle an aliase loop?

command="alias b=echo
alias a=b
a Hello Guillaume"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | wc -m`
nmatch2=`cat $OUTPUTFILE | wc -w`
if [ $nmatch -eq 16 ] && [ $nmatch2 -eq 2 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
